# Generated by Django 4.2.4 on 2023-08-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_client_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='domain',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Домен'),
        ),
        migrations.DeleteModel(
            name='MailingClient',
        ),
    ]
