# Generated by Django 4.2.4 on 2023-08-31 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mailing', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['pk'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'ordering': ['pk'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'ordering': ['pk'], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
    ]
