# Generated by Django 4.2.5 on 2023-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_client_options_alter_mailinglog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='clients', to='mailing.clientgroup', verbose_name='Группы клиентов'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='mailing_settings', to='mailing.clientgroup', verbose_name='Группы рассылок'),
        ),
    ]
