# Generated by Django 4.2.5 on 2023-09-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_clientgroup_client_groups_mailingsettings_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, related_name='clients', to='mailing.clientgroup', verbose_name='Группы клиентов'),
        ),
    ]
